import Head from 'next/head'
import newStyled from '@emotion/styled'
import { css } from '@emotion/react'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={bold}>hello</div>
    </Container>
  )
}

const Container = newStyled.div`
  background-color: pink;
`
const bold = css`
  font-weight: bold;
`
